version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: booking_system
      MYSQL_USER: booking_system
      MYSQL_PASSWORD: booking_system
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  migration-flyway:
    image: flyway/flyway:8.0.5
    command:
      - -url=jdbc:mysql://db:3307 -schemas=booking_system -user=root -password=root -connectRetries=60 migrate
      - sh -c './wait-for db:3307 -- npm start'
    volumes:
      - ./sql_versions:/flyway/sql
    depends_on:
      - db
  booking-system:
    container_name: booking-system
    build:
      context: .
      dockerfile: Dockerfile
    image: booking-system:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/booking_system?createDatabaseIfNotExist=true&currentSchema=booking_system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

volumes:
  db-data:
networks:
  backend: