version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: emotional_help
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
  emotionalHelpTeam1:
    container_name: emotionalHelpTeam1
    build:
      context: .
      dockerfile: Dockerfile
    image: emotional-help:latest
    ports:
      - "8087:8087"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/emotional_help?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

networks:
  backend: