version: '3'



services:
  docker-mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      MYSQL_DATABASE: emotional_help
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  app:
    build: .
    networks:
      - backend
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/emotional_help?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - docker-mysql
networks:
  backend: