server:
  port: 8087
  application:
    name: Emotional_Help

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emotional_help?createDatabaseIfNotExist=TRUE&currentSchema=emotional_help
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: emotionalhelpteam1@gmail.com
    password: ohvmpmjzykwpzjwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    confirmLinkIP: http://localhost:8087/
jwt:
  bearer: Bearer
  # those are the expiration durations for jwt access and jwt refresh
  # introduced in milliseconds.
  accessExpirationMs: 18000000
  refreshExpirationMs: 30000000

springdoc:
  swagger-ui:
    path: /swagger-ui.html



