server:
  port: 8080
  application:
    name: Emotional_Help
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_family_tree?currentSchema=my_family_tree
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
