server:
  port: 8087
  application:
    name: Emotional_Help
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emotional_help?createDatabaseIfNotExist=TRUE&currentSchema=emotional_help
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
