server:
  port: 8087
  application:
    name: Emotional_Help

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emotional_help?createDatabaseIfNotExist=TRUE&currentSchema=emotional_help
    driver-class-name: com.mysql.cj.jdbc.Driver
    datasource:
      initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 465
    class: javax.net.ssl.SSLSocketFactory
    username: emotionalhelpteam1@gmail.com
    password: ohvmpmjzykwpzjwk
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    confirmLinkIP: http://localhost:4200/
  servlet:
    multipart:
      max-file-size: 50000KB
      max-request-size: 50000KB
jwt:
  bearer: Bearer
  # those are the expiration durations for jwt access and jwt refresh
  # introduced in milliseconds.
  accessExpirationMs: 80000000000
  refreshExpirationMs: 90000000000


springdoc:
  swagger-ui:
    path: /swagger-ui.html

path:
  basePackagePath: "users/avatars"





