-- MySQL Script generated by MySQL Workbench
-- Sat Dec  3 22:26:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema emotional_help
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emotional_help
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emotional_help` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `emotional_help` ;

-- -----------------------------------------------------
-- Table `emotional_help`.`questionnaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`questionnaires` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`questions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `questionnaires_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quetisonbirthdays_quizzes_idx` (`questionnaires_id` ASC) VISIBLE,
  CONSTRAINT `fk_quetisons_quizzes`
    FOREIGN KEY (`questionnaires_id`)
    REFERENCES `emotional_help`.`questionnaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`answers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quetisons_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `points` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_answers_quetisons1_idx` (`quetisons_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_quetisons1`
    FOREIGN KEY (`quetisons_id`)
    REFERENCES `emotional_help`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`results`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `emotional_help`.`results` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `questionnaires_id` BIGINT UNSIGNED NOT NULL,
  `points` INT NOT NULL,
  `short_description` VARCHAR(255) NOT NULL,
  `full_description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_results_quizzes1_idx` (`questionnaires_id` ASC) VISIBLE,
  CONSTRAINT `fk_results_quizzes1`
    FOREIGN KEY (`questionnaires_id`)
    REFERENCES `emotional_help`.`questionnaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`users`
-- -----------------------------------------------------
/*created a table that represents the user*/
CREATE TABLE IF NOT EXISTS `emotional_help`.`users`
(
    `id`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `image` VARCHAR(255),
    `name`      VARCHAR(255)       NOT NULL,
    `birthday`        DATE,
    `gender`          VARCHAR(255),
    `email`           VARCHAR(255)       NOT NULL,
    `role`            VARCHAR(255),
    `enabled`         BOOLEAN,
    `country`			VARCHAR(255),
    `blocked`         BOOLEAN,
    `password`        VARCHAR(255),
    `access_code_id`  BIGINT unsigned UNIQUE,
     PRIMARY KEY (`id`)

);

-- -----------------------------------------------------
-- Table `emotional_help`.`quiz_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`quiz_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `points` INT NOT NULL,
  `questionnaires_id` BIGINT UNSIGNED NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  `complete_date`        DATE,
  `results_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quiz_history_questionnaires1_idx` (`questionnaires_id` ASC) VISIBLE,
  INDEX `fk_quiz_history_users2_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_history_questionnaires1`
    FOREIGN KEY (`questionnaires_id`)
    REFERENCES `emotional_help`.`questionnaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_quiz_history_results1`
    FOREIGN KEY (`results_id`)
    REFERENCES `emotional_help`.`results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_history_users2`
    FOREIGN KEY (`users_id`)
    REFERENCES `emotional_help`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`articles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `full_description` TEXT NOT NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`specialists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`specialists` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `image` VARCHAR(1024) NULL,
  `info` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emotional_help`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emotional_help`.`projects` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(1024) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `emotional_help`.`access_code`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `emotional_help`.`access_code`
(
    id         BIGINT unsigned PRIMARY KEY NOT NULL AUTO_INCREMENT,
    code       VARCHAR(255)       NOT NULL,
    created_at TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE `emotional_help`.`users`
    ADD CONSTRAINT users_access_code_fk
        FOREIGN KEY (access_code_id) REFERENCES emotional_help.access_code (id)
            ON DELETE CASCADE ON UPDATE RESTRICT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
